# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapi', '0002_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
